
[[models]]
identifier = "deepseek-chat"
provider = "deepseek"
model_name = "deepseek-chat"
base_url = "https://api.deepseek.com/beta"
temperature = 0.7
max_tokens = 8192
prefill = true
context_window = 131072

[[models]]
identifier = "deepseek-reasoner"
provider = "deepseek"
model_name = "deepseek-reasoner"
base_url = "https://api.deepseek.com/beta"
temperature = 0.7
max_tokens = 65536
context_window = 131072


[[models]]
identifier = "minimax-m2.1"
provider = "minimax"
model_name = "MiniMax-M2.1"
base_url = "https://api.minimaxi.com/anthropic"
temperature = 1.0
max_tokens = 65536
context_window = 204800
think = true


[[models]]
identifier = "kimi-k2"
provider = "kimi"
model_name = "kimi-k2-0905-preview"
base_url = "https://api.moonshot.cn/v1"
temperature = 0.6
max_tokens = 262144
context_window = 262144
think = false

[[models]]
identifier = "kimi-k2-thinking"
provider = "kimi"
model_name = "kimi-k2-thinking"
base_url = "https://api.moonshot.cn/v1"
temperature = 1.0
max_tokens = 262144
context_window = 262144
think = true

[[models]]
identifier = "kimi-k2-turbo"
provider = "kimi"
model_name = "kimi-k2-turbo-preview"
base_url = "https://api.moonshot.cn/v1"
temperature = 0.6
max_tokens = 262144
context_window = 262144
think = false

[[models]]
identifier = "kimi-k2-thinking-turbo"
provider = "kimi"
model_name = "kimi-k2-thinking-turbo"
base_url = "https://api.moonshot.cn/v1"
temperature = 1.0
max_tokens = 262144
context_window = 262144
think = true

[[models]]
identifier = "mimo-v2-flash"
provider = "xiaomi"
model_name = "mimo-v2-flash"
temperature = 0.8
max_tokens = 131072
context_window = 262144

[[models]]
identifier = "mimo-v2-flash-thinking"
provider = "xiaomi"
model_name = "mimo-v2-flash"
temperature = 0.8
max_tokens = 131072
context_window = 262144
think = true